# Application Properties
spring.application.name=med-appoint-api

# Database Configuration (H2 for Testing)
spring.datasource.url=jdbc:h2:mem:med_appoint_db;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Database Configuration (PostgreSQL - Commented for now)
# spring.datasource.url=jdbc:postgresql://localhost:5432/med_appoint_db
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Server config
server.port=8081
server.error.include-message=always

# JWT Configuration (Custom properties)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Mail Configuration (Dummy for startup)
spring.mail.host=localhost
spring.mail.port=2525
spring.mail.username=user
spring.mail.password=pass
